"""Update block to Integer with check constraint

Revision ID: 0ecb01b74aa3
Revises: 7ec008fbe1f1
Create Date: 2024-08-31 01:05:56.152666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ecb01b74aa3'
down_revision = '7ec008fbe1f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timeslot', schema=None) as batch_op:
        batch_op.alter_column('block',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timeslot', schema=None) as batch_op:
        batch_op.alter_column('block',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=1),
               existing_nullable=False)

    # ### end Alembic commands ###
