"""Adjust guest participation

Revision ID: 4f5c2db0b521
Revises: 7598138da8f8
Create Date: 2024-08-11 13:14:38.901412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f5c2db0b521'
down_revision = '7598138da8f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')
        batch_op.drop_column('color')

    with op.batch_alter_table('user_meeting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Enum('moderator', 'guest', name='role_enum'), nullable=False))
        batch_op.add_column(sa.Column('color', sa.String(length=7), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_meeting', schema=None) as batch_op:
        batch_op.drop_column('color')
        batch_op.drop_column('role')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.VARCHAR(length=7), nullable=False))
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=9), nullable=False))

    # ### end Alembic commands ###
