"""add guest participation: relationship user-meet

Revision ID: 7598138da8f8
Revises: 
Create Date: 2024-08-09 12:26:15.371473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7598138da8f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_meeting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_meeting', schema=None) as batch_op:
        batch_op.drop_column('confirmed')

    # ### end Alembic commands ###
