"""Change block column to accept integer values

Revision ID: 7ec008fbe1f1
Revises: 
Create Date: 2024-08-31 00:57:57.536168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ec008fbe1f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timeslot', schema=None) as batch_op:
        batch_op.alter_column('block',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('1', '2', '3', name='block_enum', native_enum=False),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timeslot', schema=None) as batch_op:
        batch_op.alter_column('block',
               existing_type=sa.Enum('1', '2', '3', name='block_enum', native_enum=False),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)

    # ### end Alembic commands ###
